# Generated by Django 2.2.13 on 2020-06-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a recipe category (breakfast, lunch, dinner, etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the recipe', max_length=300)),
                ('ingredients', models.TextField(help_text='Enter the ingredients and the amounts of each item for this recipe', max_length=1000)),
                ('servings', models.CharField(help_text='Enter the amount of servings this recipe yields', max_length=100)),
                ('prep_time', models.CharField(help_text='Enter the amount of time this recipe takes to prepare', max_length=100)),
                ('cook_time', models.CharField(help_text='Enter the amount of time this recipe takes to cook', max_length=100)),
                ('created', models.DateField()),
                ('steps', models.TextField(help_text='Enter the step-by-step instructions to make this recipe', max_length=3000)),
                ('notes', models.TextField(blank=True, help_text='Enter any helpful tips about this recipe', max_length=300, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('category', models.ManyToManyField(help_text='Select a category for this recipe', to='catalog.Category')),
            ],
        ),
    ]
